package-lock.json
package.json
src/App.js
src/components/Community.js
src/components/Header.js
src/components/Home.js
src/components/Member.js
src/components/Store.js
src/components/Vote.js
src/components/auth/Signin.js
src/components/auth/Signup.js
src/components/interview/ChoiceInterviewMode.js
src/components/interview/Interview.js
src/components/interview/InterviewChoiceStack.js
src/components/interview/InterviewMain.js
src/components/interview/InterviewNote.js
src/components/interview/InterviewResult.js
src/components/interview/PracticeChoiceStack.js
src/components/interview/PracticeInterview.js
src/components/interview/PracticeInterviewMain.js
src/components/posts/InfoPost.js
src/components/posts/Post.js
src/components/posts/QnAPost.js
src/components/posts/UpdatePost.js
src/config.js

Feature/base route/#3

---

package-lock.json
package.json

프록시 추가 했습니다. 노션 확인 바랍니다.
안 하면 지구 끝까지 찾아갈게요

Add http-proxy-middleware

---

src/components/Header.js

- 배경색 figma에 맞춰 변경
- margin대신 padding으로 변경

Style: Header CSS 수정

---

src/App.js
src/components/Header.js

signin, singup api 경로 변경
이슈 안만들고 코드 수정해버려서 pull request하겠습니다

chore: #3 signin,signup api변경

---

package-lock.json
package.json

"MUI라이브러리 추가 "

---

src/pages/Vote.js

ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다.
ex) 여기에서 이 부분 잘 모르겠는데 한번 봐주실 수 있나요?

feat: #19 찐 완성

---

src/App.js
src/components/Header.js
src/components/posts/EditorBox.js

Rename: URL 변경

---

src/components/Header.js

창민님 Header까지 전체를 옮겨버렸는데 아직 구현중인 Header였어서 계속 alert가 뜨는 오류가 있었습니다.
(로그인 시 DTO값에 id를 넣어주셔야합니다... 근데 암호화까지 하신댔죠?화이팅)
원래의 임시 헤더로 변경했습니다

헤더 임시 헤더로 변경

---

src/components/CustomLi.js
src/components/Wrapper.js
src/pages/posts/PostDetail.js

window.location.href를 쓰니, localhost:3000 대신 바로 IP가 들어가서 api요청 경로가 잘못 되어서 생기는 오류였습니다.
useNavigate를 이용해 경로 설정을 해줬습니다.
data json 형식 위에 주석 달아놨으니 참고해서 쓰세여~

Fix: 게시글 상세 조회 오류 해결 및 기능 구현

---

src/components/Header.js
src/pages/Member.js
src/pages/auth/Signin.js

- [] 기능 추가 ✨
localStorage에 nickName추가

Rector: #16 header부분 localStorage getNickName으로 변경

---

src/pages/posts/PostDetail.js

feat: #30 게시글 조회 완성

---

src/pages/posts/PostDetail.js
src/pages/posts/UpdatePost.js

통합하면서 제대로 되지 않았던 업데이트를 수정했습니다.
이미지 처리는.....나중에할게요....

Fix: 업데이트 수정

---

src/components/Header.js
src/pages/Home.js

로그인 성공여부 없이 home페이지나 헤더에서 커뮤니티 페이지로 이동하기

Refactor: #16 커뮤니티버튼 로그인 상관없이 이동하기

---

src/pages/posts/PostInfo.js
src/pages/posts/PostQNA.js
src/pages/posts/UpdatePost.js

Fix: 업데이트 오류 해결

---

src/pages/Store.js

fix: #70 await 추가

---

package-lock.json
package.json
src/components/DisposableButton.js
src/components/modal/GlassModal.css
src/components/modal/GlassModal.js
src/components/modal/GlassModalChildren.js
src/components/posts/EditorBox.js
src/index.css
src/pages/Home.js
src/pages/Store.js
src/pages/auth/Signin.js
src/pages/interview/InterviewChoiceStack.js
src/pages/interview/InterviewMain.js
src/pages/interview/InterviewNote.js
src/pages/interview/InterviewResult.js
src/pages/interview/PracticeChoiceStack.js
src/pages/posts/PostInfo.js
src/pages/posts/PostQNA.js
src/pages/posts/UpdatePost.js

짜잘한 디자인 통일 및 버그 수정
한 번만 클릭 가능한 DisposableButton 만들었음

디자인 및 버그 수정

---

src/pages/interview/PracticeInterview.js

Fix : 면접 연습 페이지

---

src/pages/interview/InterviewResult.js

Fix: #73 inverviewResult CSS 수정

---

src/components/PageButtonController.js

feat: #80 페이지 버튼 수정

---

src/config.js
src/pages/Member.js

ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다.
ex) 여기에서 이 부분 잘 모르겠는데 한번 봐주실 수 있나요?

Feature/my page/#87

---

src/components/Header.js
src/pages/interview/InterviewNote.js
src/pages/interview/InterviewResult.js
src/pages/interview/PracticeInterview.js

* 헤더에 누락된 메뉴 추가
* 연습 모드에서 GPT 답변 제출 시 모달 클릭 1번만 되도록 ui 수정
* 마이페이지 프로필 수정 버튼 너비 수정

Fix: CSS수정 및 헤더 메뉴 추가
